### ISSUE TITLE
Budgie MPRIS Widget Feedback

### ISSUE THREAD

**Issue by JoshStrobl** [NikkNakk/Brightwork-Theme#10]
Some general feedback on the Budgie MPRIS widget support:

- Player controls are too compact
- Text is not visible with no album art, or hard to see with album art.

My suggestion would be to have a semi-opaque area behind the inner widget Gtk.Boxes to ensure consistent visibility regardless of the album art or lack thereof.

![Screenshot from 2019-06-13 23-10-40](https://user-images.githubusercontent.com/156574/59464370-e995e500-8e30-11e9-99bf-a7834239b917.png)

**Comment by JoshStrobl** [comment]
Please note that I actually have a PR ready for this and made some changes in Budgie to make it easier to theme MPRIS. ISP is just performing maintenance at the moment (typing from le phone) so can't send the PR yet :smile:  PR also includes some other general Raven improvements.

**Comment by JoshStrobl** [comment]
![Screenshot from 2019-06-14 02-33-13](https://user-images.githubusercontent.com/156574/59473841-cf6a0000-8e4c-11e9-808d-bf0a4fdd2d73.png)


:point_up_2: with PR

**Comment by NikkNakk** [comment]
Looks GREAT!
