### ISSUE TITLE
Desktop Icon's text invisible on dark background

### ISSUE THREAD

**Issue by JacekJagosz** [NikkNakk/Brightwork-Theme#11]
The text is dark grey, so it is invisible on dark backgrounds.
Tested on Solus Budgie
![Zrzut ekranu z 2019-06-13 23-40-30](https://user-images.githubusercontent.com/28653965/59469490-3da2c880-8e35-11e9-9e31-8f747cac7843.png)

**Comment by NikkNakk** [comment]
Fixed! I made desktop text more of a white color and I added a text-shadow so it will pop-out more when it is on a white background.
