### ISSUE TITLE
Close, unmaximize, and minimize buttons dont respect corner radius on hover

### ISSUE THREAD

**Issue by EbonJaeger** [NikkNakk/Brightwork-Theme#17]
Just what it says on the tin: when hovering the mouse over these buttons, they turn into full circles regardless of the set button corner radius. For some programs (VS Code, Discord, Brave, etc.) these buttons are always circles regardless of hover or not.

I attempted to fix this myself, but have been so far unsuccessful.

**Comment by NikkNakk** [comment]
Could be two things; 

1. The actual png are still round causing the issue, 

2. Sometimes you have to restart for it to take affect in programs. I know for Firefox, vscode, etc. I always have to restart for things to take affect in those headerbars. 

I think 1 is most likely, I'll will look into it.

**Comment by NikkNakk** [comment]
@EbonJaeger Fixed! Should work now. You still may need to restart to apply it to all programs.
