### ISSUE TITLE
Selected text almost invisible in Nautilus/Firefox navigation bar

### ISSUE THREAD

**Issue by Staudey** [NikkNakk/Brightwork-Theme#21]
**Describe the bug**
When you select text in the Firefox or Nautilus navigation bar (CTRL+L), there is almost no visible difference between the selected and unselected text (in fact in the case of Firefox I can't see _any_ difference at all).

**Expected behavior**
A clear contrast between selected and unselected text

**Screenshots**
Nautilus navigation bar with about half of the text selected:
![Nautilusbar](https://user-images.githubusercontent.com/6317346/59803726-ab933800-92ec-11e9-8c9d-2db184c4b3b2.png)
Firefox navigation bar with about half of the text selected:
![Firefoxbar](https://user-images.githubusercontent.com/6317346/59803733-ae8e2880-92ec-11e9-960d-0ca1b278ae56.png)

**Application and Desktop Information**
Up-to-date Solus Unstable with Firefox 67.0.3 and Nautilus 3.26.4
budgie-desktop 10.5 (git-8450ae384660c87bced67ded58c783be58a65a29)
Theme config as seen [here](https://discuss.getsol.us/d/1399-my-budgie-theme-brightwork-release/14) (but it also happens with the default settings

**Additional context**
Using the "Brightwork-Dark" theme results in this for Firefox:
![FirefoxDark](https://user-images.githubusercontent.com/6317346/59804146-c9ad6800-92ed-11e9-927e-346122be5f5a.png)
Nautlius seems to behave same as before.

**Comment by NikkNakk** [comment]
Thanks! I knew about this one, and have been lazy about fixing it haha. 

The firefox one will actually be fixed when I introduce the Firefox css, but I can also make sure it works by default (which is the responsible thing to do).

**Comment by Staudey** [comment]
Thanks for the response!
I was starting to think there was something wrong with my system because nobody else seemed to talk about this issue. Good to know it's not just me ^^
I also updated the report because I mistakenly wrote that selecting the Budgie "Dark Theme" option changes the behaviour in Firefox, when it was actually changed by choosing the "Brightwork Dark" theme.

**Comment by NikkNakk** [comment]
No problem! Fixed it for Nautilus and entry boxes elsewhere in the theme. I haven't fixed Firefox yet, but I will reopen that as a separate issue because it has to be handled differently.
