### ISSUE TITLE
No icons highlighted in ALT + TAB app switcher in Budgie

### ISSUE THREAD

**Issue by JacekJagosz** [NikkNakk/Brightwork-Theme#22]
This might be connected to other issues.
App icons aren't highlighted in app switcher, which makes it really hard to use.
![AltTab](https://user-images.githubusercontent.com/28653965/59852981-3e28eb00-9370-11e9-9a34-f6fe32c54c9c.png)
Brightwork v0.1.1 with default config
Solus Budgie with Papirus icon theme

**Comment by NikkNakk** [comment]
Fixed! Thanks!
