### ISSUE TITLE
Directory highlighting in Nautilus displays unreadable directory name

### ISSUE THREAD

**Issue by Corvus-Ruber** [NikkNakk/Brightwork-Theme#27]
**Describe the bug**
If you hover on a selected directory in Nautilus, the text is the same color of the highlight.

**Expected behavior**
A readable directory name while hovering on selected directories

**Screenshots**
Screenshot 1 (selected directory and hovering on unselected directory):
![Brightwork](https://user-images.githubusercontent.com/52621154/60765801-3ff8eb00-a0a0-11e9-97fc-fd5ac8518901.jpg)

Screenshot 2 (hovering on selected directory)
![Brightwork2](https://user-images.githubusercontent.com/52621154/60765805-5606ab80-a0a0-11e9-9860-597cd68d6938.jpg)

**Application and Desktop Information**
The theme was lightly edited from default, changing opacity, corner radius and colors.
Added modified config file
[_config.txt](https://github.com/NikkNakk/Brightwork-Theme/files/3365404/_config.txt)

**Comment by NikkNakk** [comment]
Fixed! Thanks!
