### ISSUE TITLE
There is no current date and tab highlighting in Raven.

### ISSUE THREAD

**Issue by Paphnutiy** [NikkNakk/Brightwork-Theme#29]
**Describe the bug**
There is no current date highlighting in Raven Calendar widget. Also, current tab in Raven (Applications or Notifications) is also not highlighted.

**Screenshots**
![raven_plata](https://user-images.githubusercontent.com/47450795/60870303-4078b980-a239-11e9-8fd4-9aac418cf91a.png)![raven_brightwork](https://user-images.githubusercontent.com/47450795/60870319-49698b00-a239-11e9-8221-600eb6fab63d.png)

**Application and Desktop Information**
Brightwork theme 0.2.0, Solus 4.0, budgie-desktop 10.5 (git-8450ae384660c87bced67ded58c783be58a65a29).

```
// Theme Colors

    //Primary Color
    $pick_color: 'red';

    //Personal(Accent) Color
    $ps_pick: 'red';

    //Color Mixes (amount of change between color temperatures) (Mix value)
    $temp_mix: 1; 

    //Shade  (Darkness of the primary and accent colors) (Range from 30 to 100)
    $shade: 60;
    $ps_shade: 40;
```

**Comment by Paphnutiy** [comment]
And to add up, notifications icon on the taskbar isn't highlighted when there are missed notifications.

**Comment by NikkNakk** [comment]
Thanks! Fixed it all up, at least for Raven. If you could make the taskbar a separate issue that'd be super helpful. 

Sorry for the slow response, I have been outrageously busy. I've unfortunately had little time to work on the theme outside of the larger tasks I'm working on.
