### ISSUE TITLE
Not using units is deprecated

### ISSUE THREAD

**Issue by EbonJaeger** [NikkNakk/Brightwork-Theme#3]
This isn't critical, but should be addressed some time down the line. When opening a GTK program from the CLI (for example, GEdit) the console shows a lot of GTK warnings saying that not using units for values is deprecated, assuming 'px'.

There are a few other theme warnings generated, but this one is the most prevalent. I could take care of this and PR if you want; save you the tedium.

**Comment by NikkNakk** [comment]
Yep, I meant to fix that before I uploaded and completely forgot. 

I didn't mind doing it, but If you want to PR that'd be great because I won't get a chance to look until tonight.

**Comment by EbonJaeger** [comment]
It might actually be faster if you do it. xD
It's taking longer than expected to figure out how everything goes together.

EDIT: Never mind, I got it.

**Comment by NikkNakk** [comment]
@EbonJaeger Thanks for doing that! I know, i should have remembered to got back and correct those. It was me being lazy when I was testing out different values. Appreciate the help!

**Comment by EbonJaeger** [comment]
No worries! Glad to help!
