### ISSUE TITLE
GTK RadioButtons not visible

### ISSUE THREAD

**Issue by JoshStrobl** [NikkNakk/Brightwork-Theme#5]
GTK RadioButtons are not visible, having no border and active states. This is reproducible regardless of the theme primary color (I'm using "sky" as an example but validated under "teal" as well). Can be tested in gtk3-widget-factory, GNOME Screenshots, and Nautilus (Sort menu)

![Screenshot from 2019-06-13 22:52:03](https://user-images.githubusercontent.com/156574/59463259-480d9400-8e2e-11e9-94b4-0687d4c7f425.png)

**Comment by NikkNakk** [comment]
Yep, I've been toying with if I should do outlines or darker translucent fill on those. I think I'll darken the background up on those, my worry is an outline will pull away from the flat elements. I'll try some ideas out and fix this up.

**Comment by NikkNakk** [comment]
This is also an issue with active switches too I think.

**Comment by NikkNakk** [comment]
I changed radio, checks, and slider colors to match the accent color rather than the primary color. I tried a few ideas out, and this one appeared the cleanest. I will close the issue for now.
