### ISSUE TITLE
Screenshot Selection has no opacity

### ISSUE THREAD

**Issue by JoshStrobl** [NikkNakk/Brightwork-Theme#6]
When taking a screenshot with the "Select area to grab" function (accessible in GNOME Screenshot and when using the budgie-screenshot-applet), the selection area is opaque, so you're unable to see any selection content behind it.

**Comment by NikkNakk** [comment]
Fixed! It was taking the `background-color:$bg_color` of the `.background` section. I added `background-color:$ps_color` to `window .background` that makes it more transparent as well as the accent color, which helps with some contrast.
