### ISSUE TITLE
Opinion: GTK (Popover) Menu Items are too compact

### ISSUE THREAD

**Issue by JoshStrobl** [NikkNakk/Brightwork-Theme#7]
This is just some UX feedback from interacting with GTK Menus (both from Popovers like in Nautilus), but in my opinion they are too compact and that can lend to misclicks during item selection.

![Screenshot from 2019-06-13 22:57:52](https://user-images.githubusercontent.com/156574/59463695-47293200-8e2f-11e9-9ea7-9ea908b99a6c.png)

**Comment by NikkNakk** [comment]
I can adjust the padding a bit on the menus.

**Comment by NikkNakk** [comment]
I adjusted the padding to 4px and added a hover effect.

**Comment by JoshStrobl** [comment]
Fantastic, thank you @NikkNakk
