### ISSUE TITLE
Opinion on Icon Tasklist pinned icon background

### ISSUE THREAD

**Issue by JoshStrobl** [NikkNakk/Brightwork-Theme#8]
Pinned, non-launched applications have background which conflicts with the icon itself. For example, in the screenshot below, the resulting border radius with non-circular icons such as Liferea and LBRY result in some conflicting radiuses, edges, etc. and ends up looking (in my opinion) chaotic.

![Screenshot from 2019-06-13 23-03-19](https://user-images.githubusercontent.com/156574/59463991-f49c4580-8e2f-11e9-8b68-5d479eb73ad7.png)

**Comment by NikkNakk** [comment]
Yeah it was an idea I played with to give squircle like shapes to the icons, but it only works when the dock is large enough. I think you're right about how chaotic it looks; going to remove those backgrounds.

**Comment by JacekJagosz** [comment]
Could you not remove it? I use bigger dock and it looks great and is better at signalling what apps are open than just a small dot at the bottom. Could you at least leave it as an option you can enable while compiling?

**Comment by NikkNakk** [comment]
@JacekJagosz I replied in the other thread as well. I want to keep it in somehow, but I'm going to have to investigate how to make it more functional. If we can get it working, I will definitely make it a configurable option as well.

**Comment by NikkNakk** [comment]
Added a option in the _config.scss to disable the backgrounds. I'm going to leave the issue open for now, because it still needs work.
